# Generated by Django 5.2.9 on 2025-12-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='날짜')),
                ('visitor_count', models.PositiveIntegerField(default=0, verbose_name='접속자 수')),
                ('unique_visitor_count', models.PositiveIntegerField(default=0, verbose_name='고유 접속자 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '접속자 통계',
                'verbose_name_plural': '접속자 통계',
                'ordering': ['-date'],
            },
        ),
    ]
