# Generated by Django 5.2.12 on 2026-03-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_visitorstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('author_name', models.CharField(help_text='닉네임 또는 이름', max_length=50, verbose_name='작성자명')),
                ('password', models.CharField(help_text='게시글 수정/삭제 시 사용할 비밀번호', max_length=128, verbose_name='수정/삭제 비밀번호')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '자유게시판 글',
                'verbose_name_plural': '자유게시판 글',
                'ordering': ['-created_at'],
            },
        ),
    ]
