# Generated by Django 5.2.12 on 2026-03-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_boardpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='anonymous_id',
            field=models.CharField(blank=True, db_index=True, help_text='쿠키 기반 익명 사용자 식별자', max_length=64, verbose_name='익명 ID'),
        ),
    ]
