# Generated by Django 5.2.12 on 2026-03-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_board_comments_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='boardcomment',
            new_name='main_boardc_post_id_7a37ce_idx',
            old_name='main_bc_post_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='boardnotification',
            new_name='main_boardn_recipie_1f8a91_idx',
            old_name='main_bn_recipient_read_idx',
        ),
    ]
